### PR TITLE
Update hashtag detail page to have better social sharing capabilities

### PR DESCRIPTION
**Pull request by zawilliams**
Addresses #222.

Per the Acceptance Criteria:

- [x] Adjust hashtag detail page to include the dynamically generated image of a hashtag token.
- [x] Include hashtag token string in page title
- [x] Include path to hashtag token image in social sharing links (already done in previous PR #217)
- [x] Include any other relevant Facebook and Twitter metatags (already done in previous PR #217)

A few notes:

1. Page title has been updated to be "#hashtagString | Hashtag Protocol" - wasn't sure if we want this to be something else.
2. I haven't done anything with the hashtag image that is dynamically generated. We may want to create a separate issue for that to dynamically generate it and maybe listen to the minting event and then generate the image.

### CODE REVIEW

**Comment by swaylock** [comment]
@zawilliams This is looking great.

A bit of feedback.

1. I was able to test hitting a detail page with a newly minted token. It took several seconds for the image to be generated. If we don't generate the image earlier in the token generation event (ie. Prior to visiting the HASHTAG detail page) we could add a loading animation as the image is being generated.  Perhaps this is better solved in a separate issue by having the minting event hit the API in some way behind the scenes immediately after minting? perhaps Zeppelin defender?
2. Need to adjust the meta description for the sharing card. Copy is pending...

**Comment by zawilliams** [comment]
Thanks!

> 1. I was able to test hitting a detail page with a newly minted token. It took several seconds for the image to be generated. If we don't generate the image earlier in the token generation event (ie. Prior to visiting the HASHTAG detail page) we could add a loading animation as the image is being generated.  Perhaps this is better solved in a separate issue by having the minting event hit the API in some way behind the scenes immediately after minting? perhaps Zeppelin defender?

Yeah a separate issue and Zeppelin Defender might be the route to go. It's at least an option. Need to look more into some possibilities.

**Comment by swaylock** [comment]
Here's the copy for the Meta Description. Ideally we can rotate randomly -- though if that is cumbersome, let's just go with the last one:

[HASHTAG] stored as a non-fungible token (NFT) on the blockchain.

Not your typical hashtag. This is [HASHTAG] as an NFT.

Hashtag Protocol enables social content tagging for the decentralized internet.

**Comment by zawilliams** [comment]
@swaylock - good to go.

The message will cycle only on refresh of the page or whenever you navigate to it. It will not update on every click.

**Comment by swaylock** [comment]
> @swaylock - good to go.
> 
> The message will cycle only on refresh of the page or whenever you navigate to it. It will not update on every click.

@zawilliams thanks for getting this in there -- however I think i didn't communicate the feedback well...

I actually like your initial "sharing message", the one that says "Checkout the hashtag [HASHTAG]..."

What I was referring to in the random message above was literally the meta description, or the text that appears below the image and link when you actually paste the url into a social sharing platform:

screenshot--2021 07 26-07_42_33
 
I believe this is located in the description tags? Not sure.

Also, when I tested pasting the hashtag in discord, the card comes up nicely, however it doesn't come up for twitter. I didn't test for facebook. I'm wondering if for twitter, it has to come from a fully qualified domain?

**Comment by zawilliams** [comment]
@swaylock ok, I think I've got it correct this time. Twitter and Facebook sharing messages have been updated to the old messaging and regular meta description, Twitter, and Open Graph meta tags now will have a randomly generated description whenever the page is loaded or refreshed.

**Comment by swaylock** [comment]
@zawilliams looking good! Thank you!

**Pull request merged**
