### PR TITLE
dApp Nuxt.js migration and SEO/social sharing update

### PR DESCRIPTION
**Pull request by zawilliams**
Addresses #189 and #77.

There's a good amount to sift through with this PR, but the gist is that I had to update the folder structure with a nuxt.js scaffold.

1. The stores are now namespaced and have to be called accordingly.
2. I ran into some errors with strict mode being enabled on the Vuex stores during development, so at some point we'll want to look at the cause of that. Once disabled, things were working fine.
3. I've upgraded most of the dependencies for `hashtag-dapp`, including `ethers`, `buefy`/`nuxt-buefy`, and `bulma` as well as `bnc-onboard` and `bnc-sdk`.
4. `bnc-onboard` was previously using a fork that is in the `hashtag-protocol` organization. We can likely delete that repo now that we are using the latest package from Blocknative.
5. I've moved all variations of config to `nuxt.config.js` as `env` variables and replaced references with `process.env.VARIABLE_NAME`.
6. There was an issue with setting the entire wallet object in the Vuex store, so I changed it to only set the wallet name as it was the only part of the wallet object being referenced anywhere in the code.
7. Added a new `SocialHead.vue` component which can be dropped into the template portion of any page to add social sharing title, description and image for Twitter and Open Graph per Nuxt's [example](https://nuxtjs.org/examples/seo-twitter-og)
8. For other SEO on any pages, Nuxt supports adding meta tags per page via the `head` method as documented [here](https://nuxtjs.org/docs/2.x/features/meta-tags-seo)
9. Some other small cleanup was done to some other components in the process - updated component names, unused code, etc.

### CODE REVIEW

**Comment by swaylock** [comment]
@zawilliams We need to get the yarn.lock conflict cleared up before platform will attempt a built. I'm not sure why that file would be conflicting. Any ideas?

**Comment by zawilliams** [comment]
@swaylock - I hadn't pulled the upstream before submitted the PR, so I just merged the upstream `stage` branch and now we're good to go.

**Comment by zawilliams** [comment]
@swaylock looks like the issue with failing to deploy is related to the disk size/running out of space. I'll let you take a look at that Platform stuff. I just removed some old config that was related to old files that don't exist anymore.

**Comment by swaylock** [comment]
@zawilliams so a couple items I see that would be nice to knockout with this PR:

1. The text color in the help bubbles (click the ? next to the datalenses on the dashboard), should be set to white.

Also, testing minting locally, the wallet worked nicely, and interaction with blocknative api worked as well. In one of the screens that shows during minting (and tagging) there is an animation that isn't being loaded. Here is the console error, it seems the asset isn't being loaded by nuxt properly. 

console

My guess is because nuxt only builds assets that are on pages, not dynamic popups like the txn dialogs? Not sure. Anyhow, wondering if you could take a look at that.  The asset is a lottie-svg animation. Should just work?

I'll have a look this weekend also, but perhaps you can debug a bit faster?

**Comment by swaylock** [comment]
@zawilliams nevermind on the lottie animation. I'm trying to fix that now (and forcing a rebuild also).

**Comment by zawilliams** [comment]
@swaylock the modal should be taken care of now. I switched the background from grey to white like it is in the current live app.

**Pull request merged**
