### PR TITLE
Add twitter:card meta tag

### PR DESCRIPTION
**Pull request by zawilliams**
This addresses #235.

I've tested this using https://cards-dev.twitter.com/validator and got a `ERROR: No card found (Card error)`.

I added the missing meta tags and this should fix that.

### CODE REVIEW

**Comment by zawilliams** [comment]
Can confirm the [validator](https://cards-dev.twitter.com/validator) is now showing the card correctly and with no errors. When I go to share https://app.pr-236-4wo45ci-nv7d6mu5vsflk.us-2.platformsh.site/hashtag/cyberhornet on Twitter, I'm not seeing the card show up. Wondering if it's being prevented as I'm getting an SSL cert warning.

**Comment by zawilliams** [comment]
I spoke too soon. Sharing on Twitter now shows the image card. Should be good to go.

**Comment by swaylock** [comment]
@zawilliams this is looking great. thank you for the quick fix. Also nice find on the validator...was looking for that before and couldn't find...

**Comment by swaylock** [comment]
Definitely liking the flexibility of Nuxt...

**Pull request merged**
